arm:
  left:
    shoulder: 
      servo:
        pinPWM: 10
        angle:
          min: 12
          max: 50
    muscle: 
      servo:
        pinPWM: 8
        angle:
          min: 0
          max: 0
    scapula: 
      servo:
        pinPWM: 11
        angle:
          min: 70
          max: 160 
    hand:
      wirst:
        servo:
          pinPWM: 7
          angle:
            min: 40
            max: 140
      finger:
        thumb:
          servo:
            pinPWM: 2
            angle:
              min: 36
              max: 135
        pointer:
          servo:
            pinPWM: 3
            angle:
              min: 30
              max: 137
        middle:
          servo:
            pinPWM: 4
            angle:
              min: 20
              max: 140
        ring:
          servo:
            pinPWM: 5
            angle:
              min: 40
              max: 150
        little:
          servo:
            pinPWM: 6
            angle:
              min: 30
              max: 145
  right:
    shoulder: //RAR-SH
      servo:
        pinPWM: 10
        angle:
          min: 16
          max: 50
    muscle: //RAR-MU
      servo:
        pinPWM: 8
        angle:
          min: 10
          max: 20
    scapula: // RAR-SCA
      servo:
        pinPWM: 11
        angle:
          min: 0
          max: 50
    hand:
      wirst:
        servo:
          pinPWM: 7
          angle:
            min: 0
            max: 0
      finger:
        thumb:
          servo:
            pinPWM: 2
            angle:
              min: 30
              max: 140
        pointer:
          servo:
            pinPWM: 3
            angle:
              min: 30
              max: 130
        middle:
          servo:
            pinPWM: 4
            angle:
              min: 30
              max: 140
        ring:
          servo:
            pinPWM: 5
            angle:
              min: 30
              max: 150
        little:
          servo:
            pinPWM: 6
            angle:
              min: 30
              max: 140
