head:
    neck:
      translation:
        servo:
          pinPWM: 12
          angle:
            min: 70
            max: 160
      rotation:
        servo:
          pinPWM: 13
          angle:
            min: 45
            max: 170
    mouth:
      servo:
          pinPWM: 26
          angle:
            min: 45
            max: 105
    eye:
      left:
        servo:
          pinPWM: 22
          angle:
            min: 90
            max: 150
      right:
        servo:
          pinPWM: 24
          angle:
            min: 85
            max: 130