// Generated by gencpp from file robot/Servo_ControlRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_SERVO_CONTROLREQUEST_H
#define ROBOT_MESSAGE_SERVO_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct Servo_ControlRequest_
{
  typedef Servo_ControlRequest_<ContainerAllocator> Type;

  Servo_ControlRequest_()
    : angle(0)  {
    }
  Servo_ControlRequest_(const ContainerAllocator& _alloc)
    : angle(0)  {
  (void)_alloc;
    }



   typedef uint16_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::robot::Servo_ControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::Servo_ControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_ControlRequest_

typedef ::robot::Servo_ControlRequest_<std::allocator<void> > Servo_ControlRequest;

typedef boost::shared_ptr< ::robot::Servo_ControlRequest > Servo_ControlRequestPtr;
typedef boost::shared_ptr< ::robot::Servo_ControlRequest const> Servo_ControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::Servo_ControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::Servo_ControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot': ['/home/florian/Documents/dvb_ws/DaVinciBot-InMoov/InMoov_ws/src/robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::Servo_ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::Servo_ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::Servo_ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::Servo_ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::Servo_ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::Servo_ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::Servo_ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffcccce422d555eeedf1005a7637b109";
  }

  static const char* value(const ::robot::Servo_ControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffcccce422d555eeULL;
  static const uint64_t static_value2 = 0xedf1005a7637b109ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::Servo_ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/Servo_ControlRequest";
  }

  static const char* value(const ::robot::Servo_ControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::Servo_ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 angle\n\
";
  }

  static const char* value(const ::robot::Servo_ControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::Servo_ControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_ControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::Servo_ControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::Servo_ControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_SERVO_CONTROLREQUEST_H
