// Generated by gencpp from file robot/Servo_Control.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_SERVO_CONTROL_H
#define ROBOT_MESSAGE_SERVO_CONTROL_H

#include <ros/service_traits.h>


#include <robot/Servo_ControlRequest.h>
#include <robot/Servo_ControlResponse.h>


namespace robot
{

struct Servo_Control
{

typedef Servo_ControlRequest Request;
typedef Servo_ControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Servo_Control
} // namespace robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot::Servo_Control > {
  static const char* value()
  {
    return "914915d0b64fe2ea004b3cbed7ecc77f";
  }

  static const char* value(const ::robot::Servo_Control&) { return value(); }
};

template<>
struct DataType< ::robot::Servo_Control > {
  static const char* value()
  {
    return "robot/Servo_Control";
  }

  static const char* value(const ::robot::Servo_Control&) { return value(); }
};


// service_traits::MD5Sum< ::robot::Servo_ControlRequest> should match 
// service_traits::MD5Sum< ::robot::Servo_Control > 
template<>
struct MD5Sum< ::robot::Servo_ControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot::Servo_Control >::value();
  }
  static const char* value(const ::robot::Servo_ControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::Servo_ControlRequest> should match 
// service_traits::DataType< ::robot::Servo_Control > 
template<>
struct DataType< ::robot::Servo_ControlRequest>
{
  static const char* value()
  {
    return DataType< ::robot::Servo_Control >::value();
  }
  static const char* value(const ::robot::Servo_ControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot::Servo_ControlResponse> should match 
// service_traits::MD5Sum< ::robot::Servo_Control > 
template<>
struct MD5Sum< ::robot::Servo_ControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot::Servo_Control >::value();
  }
  static const char* value(const ::robot::Servo_ControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::Servo_ControlResponse> should match 
// service_traits::DataType< ::robot::Servo_Control > 
template<>
struct DataType< ::robot::Servo_ControlResponse>
{
  static const char* value()
  {
    return DataType< ::robot::Servo_Control >::value();
  }
  static const char* value(const ::robot::Servo_ControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MESSAGE_SERVO_CONTROL_H
