// Generated by gencpp from file robot/test.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_TEST_H
#define ROBOT_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct test_
{
  typedef test_<ContainerAllocator> Type;

  test_()
    : a(0)  {
    }
  test_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int16_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::robot::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::test_<ContainerAllocator> const> ConstPtr;

}; // struct test_

typedef ::robot::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::robot::test > testPtr;
typedef boost::shared_ptr< ::robot::test const> testConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::test_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot': ['/home/florian/Documents/dvb_ws/DaVinciBot-InMoov/InMoov_ws/src/robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55dc7b156d5624062efec16350895ec2";
  }

  static const char* value(const ::robot::test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55dc7b156d562406ULL;
  static const uint64_t static_value2 = 0x2efec16350895ec2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/test";
  }

  static const char* value(const ::robot::test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 a\n\
";
  }

  static const char* value(const ::robot::test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::test_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int16_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_TEST_H
